name: geolocator
description: Geolocation plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API for generic location (GPS etc.) functions.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 9.0.2

publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: geolocator_android
      ios:
        default_package: geolocator_apple
      macos:
        default_package: geolocator_apple
      web:
        default_package: geolocator_web
      windows:
        default_package: geolocator_windows

git_base_url: &GIT_BASE_URL git@github.com:TimurDyushaliev/flutter-geolocator.git

dependencies:
  flutter:
    sdk: flutter
  
  geolocator_platform_interface:
    git:
      url: *GIT_BASE_URL
      path: geolocator_platform_interface
  geolocator_android:
    git:
      url: *GIT_BASE_URL
      path: geolocator_android
  geolocator_apple:
    git:
      url: *GIT_BASE_URL
      path: geolocator_apple
  geolocator_web:
    git:
      url: *GIT_BASE_URL
      path: geolocator_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mockito: ^5.0.0-nullsafety.7
  plugin_platform_interface: ^2.0.0
